### ISSUE TITLE
Failed to connect

### ISSUE THREAD

**Issue by WorldOfMaze** [dwradcliffe/home-assistant-waterguru#1]
Thank you for building this!!!  I have been using WaterGuru for several years and have been looking for a way to integrate it with Home Assistant.  I tried to get WaterGuru-API to work in Docker with little success.  I tried your integration and, with one minor exception, get it up and running easily.  The only issue I had is that the email address needs to be enter in all lower case; my email contains several words so I usual use Camel case.  Since I have had this same issue with other integration, I was able to get this sorted pretty quickly.

Thank you again for porting WaterGuru-API to HACS.

**Comment by dwradcliffe** [comment]
You're welcome!

I addressed the lowercase email in https://github.com/dwradcliffe/home-assistant-waterguru/commit/de757e89780c1d5db941970da2ef8be57ff4a43d
