### ISSUE TITLE
Incorrect Cassete Days Remaining

### ISSUE THREAD

**Issue by WorldOfMaze** [dwradcliffe/home-assistant-waterguru#2]
In the WaterGuru app -- both on the phone and desktop/web -- the cassette is showing 20 days left while the integration is showing 10 day.  Does this depend on the WaterGuru model?  I have the original SENSE that just monitors pH and Free Chlorine.  If it turns out that the integration is always one-half of what the app shows, I can easily account for this.

Thanks again for making this available, David.

**Comment by dwradcliffe** [comment]
You're totally right. I hardcoded the math based on my S2 with the C5 cassettes. The device model doesn't actually matter, but the current cassette type does. I'll try to figure out how to tell the difference.

**Comment by dwradcliffe** [comment]
Ok this should be fixed now in https://github.com/dwradcliffe/home-assistant-waterguru/commit/d9906c09bd5e82768937eded81e01a72884d1ac9

Please re-open if that doesn't solve it.

**Comment by WorldOfMaze** [comment]
@dwradcliffe Thanks for the quick response.  I have downloaded the latest package and the HA results match the WatarGuru app perfects.
