### ISSUE TITLE
ENHANCEMENT: Add Last Measurement Time

### ISSUE THREAD

**Issue by WorldOfMaze** [dwradcliffe/home-assistant-waterguru#3]
It appears that the WaterGuru-API returns values for `latestMeasureTime` and `latestMeasureTimeHuman`.  It would be great if this were added to the HACS Integration, either as attributes to entity or as a new sensor.

If you need more info, please let me know.

Thanks.

**Comment by soleen** [comment]
Is this API only to see measurement time or is it also to set t?

**Comment by Scope666** [comment]
I believe it's a read-only value, telling you the last time a test was run:

![image](https://github.com/dwradcliffe/home-assistant-waterguru/assets/31927547/40f85527-223e-40e6-af12-f985bff683cb)

This is another one that would be great to expose, the overall "status" of the pool:   (green, yellow or red)

![image](https://github.com/dwradcliffe/home-assistant-waterguru/assets/31927547/625ea6ff-3758-4d0a-bb0a-623bd8d4ee36)

**Comment by soleen** [comment]
Makes sense. I wish there was a way to also set the time of checking (as it is allowed to do in the app).
This way, we could possibly automate cassette saving cheating: by changing the test time.
For example test time 7am, and at 6:30am, you change the test time to 6am, and therefore test is skipped on that day ..

**Comment by Scope666** [comment]
Ah, yeah, that would be cool ... not sure if the API would allow that.  I thought you meant when the last test was performed, not the "measurement time" you set under settings.

**Comment by dwradcliffe** [comment]
Latest measurement times are now added as an attribute to all sensors. There is also a new sensor for the overall status.

**Comment by Scope666** [comment]
> Latest measurement times are now added as an attribute to all sensors. There is also a new sensor for the overall status.

Wow, you ROCK!!!  ... Thank you!!!     :-)

**Comment by WorldOfMaze** [comment]
I upgraded to `a123686`.  I can see `last_measurement` in 6 of the sensors:  Free Chlorine, pH and skimmer and their corresponding alerts which is great.  However, I do not see a "sensor" for Last Measurement Time.  Not important as I have the data in the attributes.

Thanks for getting  this done.  I use the integration daily and can now pretty much ditch the WaterGuru app.  The only thing I need to app for is the let WaterGuru know when I change the cartridge.
