### ISSUE TITLE
Install errors : cannot import name 'ConfigFlowResult' from 'homeassistant.config_entries' 

### ISSUE THREAD

**Issue by ChrisTFSB** [dwradcliffe/home-assistant-waterguru#4]
Thanks for writing this integration - excited to add it to my config.

When adding the integration it errors, with the logs below.

Running on Synology NAS using Docker:
```
Home Assistant

Core
2024.2.3
Frontend
20240207.1
```

```
Log details (ERROR)
Logger: homeassistant.config_entries
Source: config_entries.py:2275
First occurred: 18:58:03 (4 occurrences)
Last logged: 20:01:27

Error occurred loading flow for integration waterguru: cannot import name 'ConfigFlowResult' from 'homeassistant.config_entries' (/usr/src/homeassistant/homeassistant/config_entries.py)
Error occurred loading flow for integration waterguru: Exception importing custom_components.waterguru.config_flow
```

**Comment by dwradcliffe** [comment]
It seems some of the internals were refactored in recent months. I'm using the "correct" classes but that means that **this integration requires Core version 2024.4 or later**.

Sorry for your trouble, but once you upgrade it should work!

**Comment by ChrisTFSB** [comment]
Thanks David, you're right - a quick update to 2024.5.2 and all is working!  Thx again.
