### ISSUE TITLE
Integration stops working if second pool is created

### ISSUE THREAD

**Issue by OtisPresley** [dwradcliffe/home-assistant-waterguru#8]
I am thinking of getting another WaterGuru for the spa, so I added a new pool. When I did, the HA integration stopped working. I deleted the integration, restarted HA, and tried again. When it tries to authenticate the account, it encounters an unknown error. As soon as I delete the second pool, it authenticates fine and works as expected.

**Comment by dwradcliffe** [comment]
Good catch. Try updating to the latest version.
Fixed in https://github.com/dwradcliffe/home-assistant-waterguru/commit/32424b4705beccb3c753829cb9c75835f05a659d

**Comment by OtisPresley** [comment]
Thanks @dwradcliffe! I downloaded the new version and verified it works. Thank you!
